name: 'Step setup'
description: 'Setup common steps used by other steps'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.4
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
        **/build/**
      key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      restore-keys: ${{ runner.os }}-gradle-
    - name: Setup Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11