name: Build + Check + APK Stats

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Install dependencies
        run: ./gradlew dependencies --stacktrace --scan
      - name: Validate Database schema changes
        run: |
          ./gradlew generateLiveReleaseDatabaseSchema --stacktrace --scan
          if [[ $(git diff --stat) != '' ]]; then
            echo "> Error: Database schema changed without adding a migration."
            exit 1
          else
            ./gradlew verifySqlDelightMigration --stacktrace --scan
          fi
      - name: Quality checks
        run: ./gradlew lint --stacktrace --scan
      - name: Unit Test
        run: ./gradlew test --stacktrace --scan
      - name: Assemble Release
        run: ./gradlew clean assembleLiveRelease bundleLiveRelease --stacktrace --scan

      - name: Decrypt secrets
        run : |
          openssl aes-256-cbc -d -md sha512 -salt -pbkdf2 -iter 10000 -in enc/release.keystore.aes -out signing/release.keystore -k ${{ secrets.PLAYGROUND_ENCRYPT_KEY }}
          openssl aes-256-cbc -d -md sha512 -salt -pbkdf2 -iter 10000 -in enc/enc.properties.aes -out enc.properties -k ${{ secrets.PLAYGROUND_ENCRYPT_KEY }}
      - name: Assemble Release
        run: ./gradlew clean assembleLiveRelease bundleLiveRelease --stacktrace --scan
      - name: Archive APKs
        run: |
          cp app/build/outputs/apk/live/release/*.apk release-${{ github.sha }}.apk
          cp app/build/outputs/bundle/liveRelease/*.aab release-${{ github.sha }}.aab
      - name: Upload archived assets
        uses: actions/upload-artifact@v2.2.1
        with:
          name: build-archive
          path: |
            release-${{ github.sha }}.apk
            release-${{ github.sha }}.aab
          retention-days: 1
      - name: Push APK to assets/master
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.name "Github Action"
          git config user.email "elliot.tormey@gmail.com"
          git checkout --orphan assets/master
          git rm --cached -r .
          cp -R app/build/outputs/apk/live/release/. assets
          cp -R app/build/outputs/bundle/liveRelease/. assets
          git add assets
          git commit -m 'add assets from ${{ github.sha }}'
          git push -f origin assets/master

      - name: Remove encrypted files
        if: always()
        run: |
          rm -rf signing/release
          rm -rf enc.properties

  apk-stats:
    if: ${{ github.event_name == 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Download Action APK
        uses: actions/download-artifact@v2.0.6
        with:
          name: build-archive
      - name: Download Latest assets from assets/master
        run: git fetch origin && git checkout origin/assets/master assets/

      - name: Run diffuse
        run: |
          .github/bin/diffuse-0.1.0-binary.jar diff assets/*.apk release-${{ github.sha }}.apk > apk-diff-${{ github.sha }}.txt
          .github/bin/diffuse-0.1.0-binary.jar diff assets/*.aab release-${{ github.sha }}.aab > aab-diff-${{ github.sha }}.txt
      - name: Prepare PR comment
        run: |
          printf "### Diffuse stats for \`$(echo ${GITHUB_BASE_REF} | cut -c1-7)\` ➡ $(echo ${GITHUB_SHA} | cut -c1-7) \n\n\`\`\`\n" > apk-pr-comment.txt && sed '/====   DEX   ====/q' apk-diff-${{ github.sha }}.txt | tac | sed "1,2d" | tac | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba' >> apk-pr-comment.txt && echo "\`\`\`"  >> apk-pr-comment.txt
          printf "### Diffuse stats for \`$(echo ${GITHUB_BASE_REF} | cut -c1-7)\` ➡ $(echo ${GITHUB_SHA} | cut -c1-7) \n\n\`\`\`\n" > aab-pr-comment.txt && sed '/====   DEX   ====/q' aab-diff-${{ github.sha }}.txt | tac | sed "1,2d" | tac | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba' >> aab-pr-comment.txt && echo "\`\`\`"  >> aab-pr-comment.txt
      - name: Add APK diff
        uses: machine-learning-apps/pr-comment@1.0.0
        with:
          path: apk-pr-comment.txt
      - name: Add AAB diff
        uses: machine-learning-apps/pr-comment@1.0.0
        with:
          path: aab-pr-comment.txt
      - name: Upload full diff
        uses: actions/upload-artifact@v2.2.1
        with:
          name: diff-report
          path: |
            apk-diff-${{ github.sha }}.txt
            aab-diff-${{ github.sha }}.txt